# ANN

In [6]:
import numpy as np

In [7]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [8]:
x = np.array([[0.05],
              [0.10]])
y = np.array([0.01])

In [9]:
# Input vector (a^{(0)})
a_0 = x

# Weight matrix for hidden layer (W^{(1)}) – shape (3, 2) 
# #Would not know these weights ahead of time in a real world application, random numbers initially then adjust them based on results
W1 = np.array([[0.15, 0.20],
               [0.25, 0.30],
               [0.35, 0.40]])

# Bias vector for hidden layer (b^{(1)}) – shape (3, 1)
b1 = np.array([[0.35],
               [0.35],
               [0.35]])

# Weight matrix for output layer (W^{(2)}) – shape (1, 3)
W2 = np.array([[0.40, 0.45, 0.50]])

# Bias vector for output layer (b^{(2)}) – shape (1, 1)
b2 = np.array([[0.60]])

## Forward-Pass

In [10]:
z1 = np.dot(W1, a_0) + b1 # Matrix multiplication using numpy # could also use: z1 = W1 @ a0 + b1 # which is built into python
a1 = sigmoid(z1)

In [11]:
z2 = np.dot(W2, a1) + b2
a2 = sigmoid(z2)

In [12]:
print(f'HIDDEN LAYER - Pre-Activations: \n z1 = \n {z1}')
print(f'HIDDEN LAYER - Activations: \n a1 =  \n {a1}')
print(f'OUTPUT LAYER - Pre-activations: \n z2 = \n {z2}')
print(f'OUTPUT LAYER - Activations: \n a2 =  \n {a2}') # network output in this example

HIDDEN LAYER - Pre-Activations: 
 z1 = 
 [[0.3775]
 [0.3925]
 [0.4075]]
HIDDEN LAYER - Activations: 
 a1 =  
 [[0.59326999]
 [0.59688438]
 [0.60048827]]
OUTPUT LAYER - Pre-activations: 
 z2 = 
 [[1.4061501]]
OUTPUT LAYER - Activations: 
 a2 =  
 [[0.803158]]


In [13]:
## Another way to print the output
print('HIDDEN LAYER 1:')
for n in range(len(z1)):
    print(f' * Neuron {n+1}:')
    print(f'    z = {z1[n]}')
    print(f'    a = {a1[n]}')
    
print('OUTPUT LAYER 2:')
for n in range(len(z2)):
    print(f' * Neuron {n+1}:')
    print(f'    z = {z2[n]}')
    print(f'    a = {a2[n]}')   

HIDDEN LAYER 1:
 * Neuron 1:
    z = [0.3775]
    a = [0.59326999]
 * Neuron 2:
    z = [0.3925]
    a = [0.59688438]
 * Neuron 3:
    z = [0.4075]
    a = [0.60048827]
OUTPUT LAYER 2:
 * Neuron 1:
    z = [1.4061501]
    a = [0.803158]


### Loss Calculation

In [14]:
print(f'Network Output: a2 = {a2}')
print(f'Desired Output: y = {y}')

error = a2-y

loss_simple = 0.5*(a2-y)**2
loss_matrix = 0.5 * np.dot(error.T, error)

print(f'Loss (Simple) = {loss_simple.item()}')
print(f'Loss (Matrix) = {loss_matrix.item()}')

Network Output: a2 = [[0.803158]]
Desired Output: y = [0.01]
Loss (Simple) = 0.3145498095005328
Loss (Matrix) = 0.3145498095005328


## Backward Pass

In [15]:
def sigmoid_derivative(z): # we not be expected to know how to calculate the derivative it will be given
    s = sigmoid(z)
    return s * (1 - s)

In [16]:
delta2 = (a2 - y) * sigmoid_derivative(z2)
print("Output layer error delta2:", delta2)

Output layer error delta2: [[0.12539449]]


In [17]:
delta1 = (W2.T @ delta2) * sigmoid_derivative(z1)
print("Hidden layer error delta1:\n", delta1)

Hidden layer error delta1:
 [[0.01210311]
 [0.01357722]
 [0.0150412 ]]


In [18]:
eta = 0.5 #chosen by the user

#Output layer update
W2 = W2 - eta * delta2 @ a2.T      # update weights
b2 = b2 - eta * delta2             # update bias
#Hidden layer update
W1 = W1 - eta * delta1 @ a_0.T      # update weights
b1 = b1 - eta * delta1             # update biases


print("Updated W2:\n", W2)
print("Updated b2:\n", b2)
print("Updated W1:\n", W1)
print("Updated b1:\n", b1)

Updated W2:
 [[0.3496442 0.3996442 0.4496442]]
Updated b2:
 [[0.53730275]]
Updated W1:
 [[0.14969742 0.19939484]
 [0.24966057 0.29932114]
 [0.34962397 0.39924794]]
Updated b1:
 [[0.34394844]
 [0.34321139]
 [0.3424794 ]]


## Another way to Structure Notebook (Better Way)

In [19]:
import numpy as np
x = np.array([[0.05],
              [0.10]])
y = np.array([0.01])
a0 = x
 
W1 = np.array([[0.15, 0.20],
               [0.25, 0.30],
               [0.35, 0.40]])
b1 = np.array([[0.35],
               [0.35],
               [0.35]])
 
W2 = np.array([[0.40, 0.45, 0.50]])
b2 = np.array([[0.60]])
 
eta = 0.5
 

In [20]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
 
def sigmoid_derivative(z):
    s = sigmoid(z)
    return s * (1 - s)

In [27]:
# Only re-run ONLY this cell to see how the algorithm improves over different passes (epoch(s))
# 1. FORWARD PASS
z1 = W1 @ x + b1
a1 = sigmoid(z1)
z2 = W2 @ a1 + b2
a2 = sigmoid(z2)
 
# 2. CALCULATE LOSS
error = a2-y
loss = 0.5 * error.T @ error
 
# 3. BACKWARD PASS
delta2 = (a2 - y) * sigmoid_derivative(z2)
delta1 = (W2.T @ delta2) * sigmoid_derivative(z1)
 
W2 = W2 - eta * delta2 @ a1.T      
b2 = b2 - eta * delta2                    
W1 = W1 - eta * delta1 @ a0.T     
b1 = b1 - eta * delta1   
 
print(f'Loss: {loss} & Output: {a2}')

Loss: [[0.21627497]] & Output: [[0.66768528]]
